CREATE TABLE FACT_POS (
DATE_ID INTEGER NOT NULL,
ITEM_ID VARCHAR(20) NOT NULL,
STORE_ID INTEGER NOT NULL,
CUSTOMER_ID INTEGER,
TRANSACTION_ID VARCHAR(30) NOT NULL,
PROMOTION_ID INTEGER,
SALES_QUANTITY INTEGER NOT NULL,
SALES_DOLLAR_AMOUNT DOUBLE NOT NULL,
COST_DOLLAR_AMOUNT DOUBLE NOT NULL
)