CREATE TABLE ITEM_DIM (
ID VARCHAR(20) PRIMARY KEY,
CATEGORY INTEGER,
SUB_CATEGORY INTEGER,
DESCRIPTION VARCHAR(1000),
ASIN CHAR(10) UNIQUE NOT NULL,
BRAND INTEGER,
UNIT_COST NUMBER NOT NULL,
UNIT_PRICE NUMBER NOT NULL,
STATUS INTEGER NOT NULL,
LAST_MODE_DATE DATE,
ADDED_DATE DATE)



