  CREATE TABLE SYSTEM.LOCATION_DIM (
    ID INTEGER PRIMARY KEY,
    COUNTRY VARCHAR(5) NOT NULL,
    CITY VARCHAR(500) NOT NULL,
    POSTAL_CODE VARCHAR(500),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    METRO_CODE INTEGER,
    AREA_CODE INTEGER,
    PROVINCE_NAME VARCHAR(20),
    METRO_NAME VARCHAR(500)
  )