  CREATE TABLE SPORTMART.SESSION_ITEMS (
    SESSION_NUM VARCHAR(50) NOT NULL,
    IP VARCHAR(15) NOT NULL,
    REQUEST_MS BIGINT NOT NULL,
    START_MS BIGINT NOT NULL,
    END_MS BIGINT NOT NULL,
    REQUESTED_PAGE VARCHAR(500) NOT NULL,
    SESSION_LENGTH BIGINT NOT NULL,
    ITEM_LOOKUP VARCHAR(20) NOT NULL,
    IP_NUM BIGINT NOT NULL
  )