CREATE TABLE STORE_DIM (
  ID INT primary key,
  RETAILER_CD VARCHAR(15),
  STORE_DESC VARCHAR(50),
  STORE_ABBR VARCHAR(50),
  STORE_TYPE VARCHAR(30),
  STORE_NAME VARCHAR(50),
  ADDRESS_1 VARCHAR(75),
  ADDRESS_2 VARCHAR(50),
  CITY VARCHAR(75),
  STATE VARCHAR(20),
  ZIP_CODE VARCHAR(15),
  AREA_CODE VARCHAR(5),
  PHONE_NUM VARCHAR(10),
  ADD_DATE DATE ,
  LAST_MOD_DATE DATE ,
  CLOSED_DATE DATE,
  REGION VARCHAR(20) NOT NULL
)
